Upgrade go-fuse (fixes #595)
rfjakob/gocryptfs pull request #690
Opened 2022-09-07 23:18 UTC by valeriangalliat

Ran `go get -u github.com/hanwen/go-fuse/v2@master` to get this diff

As pointed out in https://github.com/rfjakob/gocryptfs/issues/595#issuecomment-1222271612, go-fuse was updated with a patch to allow `-reverse` mode on macOS!

2022-10-21 20:23 UTC, rfjakob requested changes
Hi, thanks for the PR!

It's good, but could you update it with two things:

1) The PR description text is very good, but the commit message is a little short ;)
Use the PR description text as the commit message.

2) go-fuse has had a new commit in the meantime, please use this latest version.

2022-11-26 14:57 UTC, valeriangalliat commented
Updated go-fuse to the latest `master` version and updated the commit message :)

2022-11-27 09:18 UTC, rfjakob commented
Merged as https://github.com/rfjakob/gocryptfs/commit/0ec7ffbfe96887f25feb7fda60b984ea18a42e0f , thanks!

(you missed a "go mod tidy" to get rid of the old references, did that for you)

2022-11-27 09:18 UTC, closed without merging

2023-03-04 12:51 UTC, rfjakob commented
For posterity: The commit on go-fuse that fixes this is https://github.com/hanwen/go-fuse/commit/58a7e145ff0d052afbbf8bb53120572b99c7faaf