Update /x/crypto, /x/sys/, /x/term, jacobsa-crypto
rfjakob/gocryptfs pull request #787
Opened 2023-09-06 20:59 UTC by paralin

Updated jacobsa-crypto which also pulls in the latest versions of the golang.org/x/ packages.

2023-09-21 01:16 UTC, paralin commented
@rfjakob rebased

2023-10-15 10:53 UTC, rfjakob requested changes

2023-10-15 10:53 UTC, rfjakob commented on .github/workflows/ci.yml
> +          - "1.21.x" # Ubuntu 22.04 LTS "jammy"
Ubuntu comment seems bogus

2023-10-16 19:12 UTC, paralin commented on .github/workflows/ci.yml
> +          - "1.21.x" # Ubuntu 22.04 LTS "jammy"
Fixed by removing the comment altogether as upstream might change what version each Go tag refers to at any time anyway.

2023-10-16 19:12 UTC, paralin commented
@rfjakob Fixed your comment.

2023-10-29 12:11 UTC, rfjakob commented
Merged as https://github.com/rfjakob/gocryptfs/commit/5da40e7adf3bd0e9097b6e5b3c793ccc65d251cc, thanks!

2023-10-29 12:11 UTC, closed without merging