init_dir: use masterkey arg
rfjakob/gocryptfs pull request #831
Opened 2024-03-09 15:12 UTC by pmazzini

Fixes #824

2024-03-12 14:34 UTC, rfjakob commented
Code change is good, but needs a test. Can you add TestInitMasterkey similar to https://github.com/rfjakob/gocryptfs/blob/master/tests/cli/cli_test.go#L77 ?

2024-03-12 14:34 UTC, rfjakob requested changes
Code change is good, test is needed

2024-03-13 00:20 UTC, pmazzini commented on cli_args.go
> -	if len(args.extpass) > 0 && args.masterkey != "" {
From https://github.com/rfjakob/gocryptfs/commit/295d432175292dbaef572093d784aab55f5c0b8f I don't see why can't these 2 be used together.

2024-03-13 09:42 UTC, merged

2024-03-13 09:43 UTC, rfjakob commented
Merged, thanks!